### ISSUE TITLE
rename `new` as `init`

### ISSUE THREAD

**Issue by townofdon** [teamairship/airfoil#14]
What do we think about using `airfoil init` in lieu of `airfoil new`?

My reasoning: match `react-native init` as closely as possible.

I'm not married to the idea, just a thought. Let me know yours!

**Comment by jonesaustindev** [comment]
I'm good with this naming instead if we wanted to re-vist this

**Comment by makozlo** [comment]
This sounds good to me. I think it helps remove confusion from some of the commands: we have `create`, `new`, and `add`. Go for it!

**Comment by makozlo** [comment]
Just submitted a PR for this.

**Comment by townofdon** [comment]
This issue addressed in PR #28
