### ISSUE TITLE
Add support for cocoapods installed through homebrew

### ISSUE THREAD

**Issue by jonesaustindev** [teamairship/airfoil#21]
When running `airfoil new testApp`, I am getting an error saying cocoapods must be installed. I ran `brew reinstall cocoapods` and tried the `new` command again, but I had the same error again. I uninstalled via homebrew, and I installed cocoapods with the ruby gem instead. This now made it work, but I could see others having cocoapods through homebrew and this causing potential issues.

**Comment by townofdon** [comment]
Thanks for documenting this issue. :) Seems to be an issue with local machine config and not airfoil specifically. Closing since it there is a solid workaround in place.
