### ISSUE TITLE
`airfoil generate component` doesn't match existing components with export

### ISSUE THREAD

**Issue by jonesaustindev** [teamairship/airfoil#24]
## Expected results

What did you expect to happen?
Components that come with Airfoil are exported as defaults and the new components should match the same style.

## Observed results

What happened?
`airfoil generate component` creates a component with the structure like so:
```
type Props = {};

export const Webview: FC<Props> = () => {
  return (
    <></>
  );
};

const styles = StyleSheet.create({});
```

Instead of similar to the existing View:
```
const View: React.FC<Props> &
  ForwardRefExoticComponent<any> = React.forwardRef(
  ({ row, style, marginTop, marginBottom, ...props }, ref: any) => (
    <RNView
      style={[
        marginTop ? { marginTop } : null,
        marginBottom ? { marginBottom } : null,
        row ? styles.row : null,
        style,
      ]}
      {...props}
      ref={ref}
    />
  ),
);

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});

export default View;
```

### Logs

Please add the log output here.

## Steps to reproduce

1. `airfoil g component`

**Comment by townofdon** [comment]
Is the issue here that the export is a named export instead of the default export? We decided to opt in favor of named exports for several reasons (better intellisense auto-imports behavior for one). I'll let @makozlo weigh in here.

**Comment by jonesaustindev** [comment]
Either way is fine @townofdon but the included components should match then for consistency. From starting up a project to using the generate, it was clear with this what is the correct style we want to go with.

**Comment by jonesaustindev** [comment]
But, with no index files what's the advantage of the named exports? Intellisense seems to work the same both ways.

**Comment by townofdon** [comment]
@jonesaustindev Ok, that makes sense. This issue should be created on https://github.com/teamairship/airfoil-schematics/ instead since that's where the change would need to be made.

**Comment by townofdon** [comment]
> But, with no index files what's the advantage of the named exports? Intellisense seems to work the same both ways.

This is a good reference for why named exports are better in general: https://basarat.gitbook.io/typescript/main-1/defaultisbad

**Comment by jonesaustindev** [comment]
Ok I'll move the issue over to the schematics to get everything matched up correctly!
