### ISSUE TITLE
Dependencies not installed when installing from NPM.

### ISSUE THREAD

**Issue by t2** [teamairship/airfoil#30]
## Expected results

All required dependencies would be installed when I installed the package. 

## Observed results

Dependencies were not installed and the CLI does not function. I see the required dependencies are in the devDependencies object in package.json instead of the dependencies object.

## Steps to reproduce

1. npm install @airship/airfoil -g
2. Run any airfoil command

**Comment by townofdon** [comment]
Fixed in https://github.com/teamairship/airfoil/pull/32
