### ISSUE TITLE
ADR apostrophes are HTML encoded

### ISSUE THREAD

**Issue by makozlo** [teamairship/airfoil#48]
## Expected results

When using the `airfoil add adr` command and pressing enter on the prompts, I expect to see the prompts formatted correctly and added to the newly created ADR file.

## Observed results

The ADR gets created, but the apostrophes appear to be HTML-encoded. I've attached an example.

![CleanShot%202021-08-30%20at%2012 58 06](https://user-images.githubusercontent.com/10499188/131336302-7a4713b2-4a57-4fec-bfc0-8d1089a892eb.jpeg)

## Steps to reproduce

1. run `airfoil add adr`
2. enter a title
3. press `return` to skip the subsequent prompts
4. open the file that gets created

**Comment by townofdon** [comment]
This seems like a limitation of the toolbox `template` method. Might be a way to allow raw input as the characters in question are being escaped.

After looking into this, the `ejs` function allows options as an optional third param, but [gluegun currently does not allow any way to pass in custom options](https://github.com/infinitered/gluegun/blob/master/src/toolbox/template-tools.ts#L57).

`ejs` itself looks dubious as to whether it would allow ignoring all unescaped strings. [There is a configurable `escape` function](https://github.com/mde/ejs#options).

The simplest and easiest workaround would be simply to find all characters that are html-escaped, and convert them back to their correct strings.
